version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - pwd
      - ls
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
